### ISSUE TITLE
TypeError: curr.exdates[i].toISOString is not a function

### ISSUE THREAD

**Issue by sonicgoose** [jclarke0000/MMM-MyCalendar#25]
I deleted some events from my O365 calendar (shared via .ics url) and now I'm getting this error loading that module:

```
Whoops! There was an uncaught exception...
TypeError: curr.exdates[i].toISOString is not a function
    at Object.ical.objectHandlers.END (/Users/met_admin/MagicMirror/modules/MMM-MyCalendar/vendor/ical.js/node-ical.js:44:44)
    at Object.handleObject (/Users/met_admin/MagicMirror/modules/MMM-MyCalendar/vendor/ical.js/ical.js:267:41)
    at Object.parseICS (/Users/met_admin/MagicMirror/modules/MMM-MyCalendar/vendor/ical.js/ical.js:308:20)
    at Request._callback (/Users/met_admin/MagicMirror/modules/MMM-MyCalendar/vendor/ical.js/node-ical.js:11:24)
    at Request.self.callback (/Users/met_admin/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/met_admin/MagicMirror/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/met_admin/MagicMirror/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
```

I have a second instance of the same module loading a second O365 calendar from the same account (different ics url, obviously) and that continues to work.

**Comment by lawrence-jeff** [comment]
Same here - deleted a bunch of events and now my outlook.com calendar doesn't load and this same error is triggered. Calendar-Ext continues to work with the same ics file

**Comment by wacher74** [comment]
+1 here.
